services:
  - type: web
    name: php-postgres-crud-test
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RENDER
        value: true
      - key: DEBUG
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-crud-test-db
          property: connectionString
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: postgres-crud-test-db
          property: password

databases:
  - name: postgres-crud-test-db
    plan: free
    ipAllowList: [] 