services:
  - type: web
    name: php-postgres-crud-test
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RENDER
        value: true
      - key: DEBUG
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-crud-test-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: postgres-crud-test-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres-crud-test-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: postgres-crud-test-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: postgres-crud-test-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres-crud-test-db
          property: password

databases:
  - name: postgres-crud-test-db
    plan: free
    ipAllowList: [] 